services:
  parser:
    build: .
    volumes:
      - /opt/parselancer/jobs.db:/workdir/jobs.db
      - /opt/parselancer/:/workdir/
    command: /workdir/run_parse.sh
#   command: bash -c "sleep 100001"
    restart: always
# sender:
# bot:

