services:
  template_srvc:
    build: .
    volumes:
      - /opt/parselancer/:/workdir/
    command: bash -c "sleep 100001"
    restart: always

  parser:
    extends:
      service: template_srvc
    command: bash -c "/workdir/run_parse.sh; sleep 30"

  sender:
    extends:
      service: template_srvc
    command: bash -c "python bot/send_alerts.py; sleep 20"

# cron:
#   build: .
#   volumes:
#     - /opt/parselancer/:/workdir/
#     - /opt/parselancer/cronjob:/etc/cron.d/cronjob
#   command: crontab /etc/cron.d/cronjob && cron && tail -f /var/log/cron.log

  bot:
    extends:
      service: template_srvc
    command: bash -c "python bot/bot.py"
    restart: always

